//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplePoso.ServicePrescribable {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="urn:Vidal", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBrandedPrescribable", Namespace="urn:Vidal", ItemName="brandedPrescribable")]
    [System.SerializableAttribute()]
    public class ArrayOfBrandedPrescribable : System.Collections.Generic.List<ExemplePoso.ServicePrescribable.brandedPrescribable> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="brandedPrescribable", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class brandedPrescribable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private System.Nullable<bool> hasKnownEffectExcipientsField;
        
        private System.Nullable<bool> homogeneousOnIndicationsField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<bool> multipleRoutesField;
        
        private string nameField;
        
        private System.Nullable<bool> safetyAlertField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> hasKnownEffectExcipients {
            get {
                return this.hasKnownEffectExcipientsField;
            }
            set {
                if ((this.hasKnownEffectExcipientsField.Equals(value) != true)) {
                    this.hasKnownEffectExcipientsField = value;
                    this.RaisePropertyChanged("hasKnownEffectExcipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> homogeneousOnIndications {
            get {
                return this.homogeneousOnIndicationsField;
            }
            set {
                if ((this.homogeneousOnIndicationsField.Equals(value) != true)) {
                    this.homogeneousOnIndicationsField = value;
                    this.RaisePropertyChanged("homogeneousOnIndications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> multipleRoutes {
            get {
                return this.multipleRoutesField;
            }
            set {
                if ((this.multipleRoutesField.Equals(value) != true)) {
                    this.multipleRoutesField = value;
                    this.RaisePropertyChanged("multipleRoutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> safetyAlert {
            get {
                return this.safetyAlertField;
            }
            set {
                if ((this.safetyAlertField.Equals(value) != true)) {
                    this.safetyAlertField = value;
                    this.RaisePropertyChanged("safetyAlert");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUcdBrandedPrescribables", Namespace="urn:Vidal", ItemName="ucdBrandedPrescribables")]
    [System.SerializableAttribute()]
    public class ArrayOfUcdBrandedPrescribables : System.Collections.Generic.List<ExemplePoso.ServicePrescribable.ucdBrandedPrescribables> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ucdBrandedPrescribables", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class ucdBrandedPrescribables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServicePrescribable.ArrayOfBrandedPrescribable brandedPrescribablesField;
        
        private ExemplePoso.ServicePrescribable.ucd ucdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServicePrescribable.ArrayOfBrandedPrescribable brandedPrescribables {
            get {
                return this.brandedPrescribablesField;
            }
            set {
                if ((object.ReferenceEquals(this.brandedPrescribablesField, value) != true)) {
                    this.brandedPrescribablesField = value;
                    this.RaisePropertyChanged("brandedPrescribables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServicePrescribable.ucd ucd {
            get {
                return this.ucdField;
            }
            set {
                if ((object.ReferenceEquals(this.ucdField, value) != true)) {
                    this.ucdField = value;
                    this.RaisePropertyChanged("ucd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ucd", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class ucd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string code13Field;
        
        private bool ghsField;
        
        private System.Nullable<float> ghsPriceField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<ExemplePoso.ServicePrescribable.MarketStatus> marketStatusField;
        
        private System.Nullable<float> maxUcdRangePriceField;
        
        private System.Nullable<float> minUcdRangePriceField;
        
        private string nameField;
        
        private bool retrocessionField;
        
        private System.Nullable<float> retrocessionPriceField;
        
        private bool safetyAlertField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code13 {
            get {
                return this.code13Field;
            }
            set {
                if ((object.ReferenceEquals(this.code13Field, value) != true)) {
                    this.code13Field = value;
                    this.RaisePropertyChanged("code13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ghs {
            get {
                return this.ghsField;
            }
            set {
                if ((this.ghsField.Equals(value) != true)) {
                    this.ghsField = value;
                    this.RaisePropertyChanged("ghs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> ghsPrice {
            get {
                return this.ghsPriceField;
            }
            set {
                if ((this.ghsPriceField.Equals(value) != true)) {
                    this.ghsPriceField = value;
                    this.RaisePropertyChanged("ghsPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServicePrescribable.MarketStatus> marketStatus {
            get {
                return this.marketStatusField;
            }
            set {
                if ((this.marketStatusField.Equals(value) != true)) {
                    this.marketStatusField = value;
                    this.RaisePropertyChanged("marketStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> maxUcdRangePrice {
            get {
                return this.maxUcdRangePriceField;
            }
            set {
                if ((this.maxUcdRangePriceField.Equals(value) != true)) {
                    this.maxUcdRangePriceField = value;
                    this.RaisePropertyChanged("maxUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> minUcdRangePrice {
            get {
                return this.minUcdRangePriceField;
            }
            set {
                if ((this.minUcdRangePriceField.Equals(value) != true)) {
                    this.minUcdRangePriceField = value;
                    this.RaisePropertyChanged("minUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool retrocession {
            get {
                return this.retrocessionField;
            }
            set {
                if ((this.retrocessionField.Equals(value) != true)) {
                    this.retrocessionField = value;
                    this.RaisePropertyChanged("retrocession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> retrocessionPrice {
            get {
                return this.retrocessionPriceField;
            }
            set {
                if ((this.retrocessionPriceField.Equals(value) != true)) {
                    this.retrocessionPriceField = value;
                    this.RaisePropertyChanged("retrocessionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool safetyAlert {
            get {
                return this.safetyAlertField;
            }
            set {
                if ((this.safetyAlertField.Equals(value) != true)) {
                    this.safetyAlertField = value;
                    this.RaisePropertyChanged("safetyAlert");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketStatus", Namespace="urn:Vidal")]
    public enum MarketStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AVAILABLE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEW = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED_ONEYEAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO_ONEYEAR = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Vidal", ConfigurationName="ServicePrescribable.prescribableService")]
    public interface prescribableService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="brandedPrescribableList")]
        ExemplePoso.ServicePrescribable.ArrayOfBrandedPrescribable searchBrandedPrescribableByIds(ExemplePoso.ServicePrescribable.ArrayOfInt brandedPrescribableIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="brandedPrescribableList")]
        ExemplePoso.ServicePrescribable.ArrayOfBrandedPrescribable searchBrandedPrescribableByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="UcdBrandedPrescribablesList")]
        ExemplePoso.ServicePrescribable.ArrayOfUcdBrandedPrescribables searchBrandedPrescribableByUcdIds(ExemplePoso.ServicePrescribable.ArrayOfInt ucdIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface prescribableServiceChannel : ExemplePoso.ServicePrescribable.prescribableService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class prescribableServiceClient : System.ServiceModel.ClientBase<ExemplePoso.ServicePrescribable.prescribableService>, ExemplePoso.ServicePrescribable.prescribableService {
        
        public prescribableServiceClient() {
        }
        
        public prescribableServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public prescribableServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public prescribableServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public prescribableServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExemplePoso.ServicePrescribable.ArrayOfBrandedPrescribable searchBrandedPrescribableByIds(ExemplePoso.ServicePrescribable.ArrayOfInt brandedPrescribableIds) {
            return base.Channel.searchBrandedPrescribableByIds(brandedPrescribableIds);
        }
        
        public ExemplePoso.ServicePrescribable.ArrayOfBrandedPrescribable searchBrandedPrescribableByName(string name) {
            return base.Channel.searchBrandedPrescribableByName(name);
        }
        
        public ExemplePoso.ServicePrescribable.ArrayOfUcdBrandedPrescribables searchBrandedPrescribableByUcdIds(ExemplePoso.ServicePrescribable.ArrayOfInt ucdIds) {
            return base.Channel.searchBrandedPrescribableByUcdIds(ucdIds);
        }
    }
}
