//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplePoso.ServiceCNG {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="urn:Vidal", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCommonNameGroupIndicators", Namespace="urn:Vidal", ItemName="commonNameGroupIndicators")]
    [System.SerializableAttribute()]
    public class ArrayOfCommonNameGroupIndicators : System.Collections.Generic.List<ExemplePoso.ServiceCNG.commonNameGroupIndicators> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commonNameGroupIndicators", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class commonNameGroupIndicators : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceCNG.commonNameGroup commonNameGroupField;
        
        private ExemplePoso.ServiceCNG.ArrayOfIndicator indicatorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceCNG.commonNameGroup commonNameGroup {
            get {
                return this.commonNameGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.commonNameGroupField, value) != true)) {
                    this.commonNameGroupField = value;
                    this.RaisePropertyChanged("commonNameGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceCNG.ArrayOfIndicator indicators {
            get {
                return this.indicatorsField;
            }
            set {
                if ((object.ReferenceEquals(this.indicatorsField, value) != true)) {
                    this.indicatorsField = value;
                    this.RaisePropertyChanged("indicators");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commonNameGroup", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class commonNameGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<float> maxUcdRangePriceField;
        
        private System.Nullable<float> minUcdRangePriceField;
        
        private string nameField;
        
        private bool notHomogeneousByInteractionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> maxUcdRangePrice {
            get {
                return this.maxUcdRangePriceField;
            }
            set {
                if ((this.maxUcdRangePriceField.Equals(value) != true)) {
                    this.maxUcdRangePriceField = value;
                    this.RaisePropertyChanged("maxUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> minUcdRangePrice {
            get {
                return this.minUcdRangePriceField;
            }
            set {
                if ((this.minUcdRangePriceField.Equals(value) != true)) {
                    this.minUcdRangePriceField = value;
                    this.RaisePropertyChanged("minUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool notHomogeneousByInteractions {
            get {
                return this.notHomogeneousByInteractionsField;
            }
            set {
                if ((this.notHomogeneousByInteractionsField.Equals(value) != true)) {
                    this.notHomogeneousByInteractionsField = value;
                    this.RaisePropertyChanged("notHomogeneousByInteractions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfIndicator", Namespace="urn:Vidal", ItemName="indicator")]
    [System.SerializableAttribute()]
    public class ArrayOfIndicator : System.Collections.Generic.List<ExemplePoso.ServiceCNG.indicator> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="indicator", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class indicator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string indicatorValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string indicatorValue {
            get {
                return this.indicatorValueField;
            }
            set {
                if ((object.ReferenceEquals(this.indicatorValueField, value) != true)) {
                    this.indicatorValueField = value;
                    this.RaisePropertyChanged("indicatorValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCommonNameGroup", Namespace="urn:Vidal", ItemName="commonNameGroup")]
    [System.SerializableAttribute()]
    public class ArrayOfCommonNameGroup : System.Collections.Generic.List<ExemplePoso.ServiceCNG.commonNameGroup> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GalenicForm", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class GalenicForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        private System.Nullable<int> parentIdField;
        
        private bool searchField;
        
        private string shortNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool search {
            get {
                return this.searchField;
            }
            set {
                if ((this.searchField.Equals(value) != true)) {
                    this.searchField = value;
                    this.RaisePropertyChanged("search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.shortNameField, value) != true)) {
                    this.shortNameField = value;
                    this.RaisePropertyChanged("shortName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfRoute", Namespace="urn:Vidal", ItemName="route")]
    [System.SerializableAttribute()]
    public class ArrayOfRoute : System.Collections.Generic.List<ExemplePoso.ServiceCNG.route> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="route", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class route : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        private System.Nullable<int> parentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Vidal", ConfigurationName="ServiceCNG.commonNameGroupService")]
    public interface commonNameGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupIndicatorsList")]
        ExemplePoso.ServiceCNG.ArrayOfCommonNameGroupIndicators searchCommonNameGroupIndicatorsByCommonNameGroupIds(ExemplePoso.ServiceCNG.ArrayOfInt commonNameGroupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupList")]
        ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByIds(ExemplePoso.ServiceCNG.ArrayOfInt commonNameGroupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupList")]
        ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByUcdId(System.Nullable<int> ucdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupList")]
        ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByAtcIds(ExemplePoso.ServiceCNG.ArrayOfInt atcIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroup")]
        ExemplePoso.ServiceCNG.commonNameGroup searchByProductId(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupList")]
        ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByActivePrincipleIds(ExemplePoso.ServiceCNG.ArrayOfInt moleculeIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="galenicForm")]
        ExemplePoso.ServiceCNG.GalenicForm getGalenicForm(System.Nullable<int> commonNameGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupList")]
        ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroup")]
        ExemplePoso.ServiceCNG.commonNameGroup searchById(System.Nullable<int> commonNameGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroup")]
        ExemplePoso.ServiceCNG.commonNameGroup searchByPackId(System.Nullable<int> packId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupList")]
        ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByAtcId(System.Nullable<int> atcId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="routeList")]
        ExemplePoso.ServiceCNG.ArrayOfRoute getRoute(System.Nullable<int> commonNameGroupId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface commonNameGroupServiceChannel : ExemplePoso.ServiceCNG.commonNameGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class commonNameGroupServiceClient : System.ServiceModel.ClientBase<ExemplePoso.ServiceCNG.commonNameGroupService>, ExemplePoso.ServiceCNG.commonNameGroupService {
        
        public commonNameGroupServiceClient() {
        }
        
        public commonNameGroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public commonNameGroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public commonNameGroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public commonNameGroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfCommonNameGroupIndicators searchCommonNameGroupIndicatorsByCommonNameGroupIds(ExemplePoso.ServiceCNG.ArrayOfInt commonNameGroupIds) {
            return base.Channel.searchCommonNameGroupIndicatorsByCommonNameGroupIds(commonNameGroupIds);
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByIds(ExemplePoso.ServiceCNG.ArrayOfInt commonNameGroupIds) {
            return base.Channel.searchByIds(commonNameGroupIds);
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByUcdId(System.Nullable<int> ucdId) {
            return base.Channel.searchByUcdId(ucdId);
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByAtcIds(ExemplePoso.ServiceCNG.ArrayOfInt atcIds) {
            return base.Channel.searchByAtcIds(atcIds);
        }
        
        public ExemplePoso.ServiceCNG.commonNameGroup searchByProductId(System.Nullable<int> productId) {
            return base.Channel.searchByProductId(productId);
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByActivePrincipleIds(ExemplePoso.ServiceCNG.ArrayOfInt moleculeIds) {
            return base.Channel.searchByActivePrincipleIds(moleculeIds);
        }
        
        public ExemplePoso.ServiceCNG.GalenicForm getGalenicForm(System.Nullable<int> commonNameGroupId) {
            return base.Channel.getGalenicForm(commonNameGroupId);
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByName(string name) {
            return base.Channel.searchByName(name);
        }
        
        public ExemplePoso.ServiceCNG.commonNameGroup searchById(System.Nullable<int> commonNameGroupId) {
            return base.Channel.searchById(commonNameGroupId);
        }
        
        public ExemplePoso.ServiceCNG.commonNameGroup searchByPackId(System.Nullable<int> packId) {
            return base.Channel.searchByPackId(packId);
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfCommonNameGroup searchByAtcId(System.Nullable<int> atcId) {
            return base.Channel.searchByAtcId(atcId);
        }
        
        public ExemplePoso.ServiceCNG.ArrayOfRoute getRoute(System.Nullable<int> commonNameGroupId) {
            return base.Channel.getRoute(commonNameGroupId);
        }
    }
}
