//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplePoso.ServiceUcd {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="urn:Vidal", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUcd", Namespace="urn:Vidal", ItemName="ucd")]
    [System.SerializableAttribute()]
    public class ArrayOfUcd : System.Collections.Generic.List<ExemplePoso.ServiceUcd.ucd> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ucd", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class ucd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string code13Field;
        
        private bool ghsField;
        
        private System.Nullable<float> ghsPriceField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<ExemplePoso.ServiceUcd.MarketStatus> marketStatusField;
        
        private System.Nullable<float> maxUcdRangePriceField;
        
        private System.Nullable<float> minUcdRangePriceField;
        
        private string nameField;
        
        private bool retrocessionField;
        
        private System.Nullable<float> retrocessionPriceField;
        
        private bool safetyAlertField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code13 {
            get {
                return this.code13Field;
            }
            set {
                if ((object.ReferenceEquals(this.code13Field, value) != true)) {
                    this.code13Field = value;
                    this.RaisePropertyChanged("code13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ghs {
            get {
                return this.ghsField;
            }
            set {
                if ((this.ghsField.Equals(value) != true)) {
                    this.ghsField = value;
                    this.RaisePropertyChanged("ghs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> ghsPrice {
            get {
                return this.ghsPriceField;
            }
            set {
                if ((this.ghsPriceField.Equals(value) != true)) {
                    this.ghsPriceField = value;
                    this.RaisePropertyChanged("ghsPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceUcd.MarketStatus> marketStatus {
            get {
                return this.marketStatusField;
            }
            set {
                if ((this.marketStatusField.Equals(value) != true)) {
                    this.marketStatusField = value;
                    this.RaisePropertyChanged("marketStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> maxUcdRangePrice {
            get {
                return this.maxUcdRangePriceField;
            }
            set {
                if ((this.maxUcdRangePriceField.Equals(value) != true)) {
                    this.maxUcdRangePriceField = value;
                    this.RaisePropertyChanged("maxUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> minUcdRangePrice {
            get {
                return this.minUcdRangePriceField;
            }
            set {
                if ((this.minUcdRangePriceField.Equals(value) != true)) {
                    this.minUcdRangePriceField = value;
                    this.RaisePropertyChanged("minUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool retrocession {
            get {
                return this.retrocessionField;
            }
            set {
                if ((this.retrocessionField.Equals(value) != true)) {
                    this.retrocessionField = value;
                    this.RaisePropertyChanged("retrocession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> retrocessionPrice {
            get {
                return this.retrocessionPriceField;
            }
            set {
                if ((this.retrocessionPriceField.Equals(value) != true)) {
                    this.retrocessionPriceField = value;
                    this.RaisePropertyChanged("retrocessionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool safetyAlert {
            get {
                return this.safetyAlertField;
            }
            set {
                if ((this.safetyAlertField.Equals(value) != true)) {
                    this.safetyAlertField = value;
                    this.RaisePropertyChanged("safetyAlert");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketStatus", Namespace="urn:Vidal")]
    public enum MarketStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AVAILABLE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEW = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED_ONEYEAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO_ONEYEAR = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UcdApiFilter", Namespace="urn:Vidal")]
    public enum UcdApiFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HORSGHS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RETROCESSION = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMarketStatus", Namespace="urn:Vidal", ItemName="MarketStatus")]
    [System.SerializableAttribute()]
    public class ArrayOfMarketStatus : System.Collections.Generic.List<System.Nullable<ExemplePoso.ServiceUcd.MarketStatus>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pagedResultUcd", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class pagedResultUcd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int pageNumberField;
        
        private int pageSizeField;
        
        private ExemplePoso.ServiceUcd.ArrayOfUcd resultField;
        
        private int rowCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.ArrayOfUcd result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int rowCount {
            get {
                return this.rowCountField;
            }
            set {
                if ((this.rowCountField.Equals(value) != true)) {
                    this.rowCountField = value;
                    this.RaisePropertyChanged("rowCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductRangeUcdCouple", Namespace="urn:Vidal", ItemName="productRangeUcdCouple")]
    [System.SerializableAttribute()]
    public class ArrayOfProductRangeUcdCouple : System.Collections.Generic.List<ExemplePoso.ServiceUcd.productRangeUcdCouple> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productRangeUcdCouple", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productRangeUcdCouple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceUcd.productRange productRangeField;
        
        private ExemplePoso.ServiceUcd.ucd ucdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.productRange productRange {
            get {
                return this.productRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.productRangeField, value) != true)) {
                    this.productRangeField = value;
                    this.RaisePropertyChanged("productRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.ucd ucd {
            get {
                return this.ucdField;
            }
            set {
                if ((object.ReferenceEquals(this.ucdField, value) != true)) {
                    this.ucdField = value;
                    this.RaisePropertyChanged("ucd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productRange", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productRange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="urn:Vidal", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyType", Namespace="urn:Vidal")]
    public enum CompanyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OWNER = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HOLDER = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISTRIBUTOR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUBSCRIBER = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUcdIndicators", Namespace="urn:Vidal", ItemName="ucdIndicators")]
    [System.SerializableAttribute()]
    public class ArrayOfUcdIndicators : System.Collections.Generic.List<ExemplePoso.ServiceUcd.ucdIndicators> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ucdIndicators", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class ucdIndicators : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string code13Field;
        
        private bool ghsField;
        
        private System.Nullable<float> ghsPriceField;
        
        private System.Nullable<int> idField;
        
        private ExemplePoso.ServiceUcd.ArrayOfIndicator indicatorsField;
        
        private System.Nullable<ExemplePoso.ServiceUcd.MarketStatus> marketStatusField;
        
        private string nameField;
        
        private bool retrocessionField;
        
        private System.Nullable<float> retrocessionPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code13 {
            get {
                return this.code13Field;
            }
            set {
                if ((object.ReferenceEquals(this.code13Field, value) != true)) {
                    this.code13Field = value;
                    this.RaisePropertyChanged("code13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ghs {
            get {
                return this.ghsField;
            }
            set {
                if ((this.ghsField.Equals(value) != true)) {
                    this.ghsField = value;
                    this.RaisePropertyChanged("ghs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> ghsPrice {
            get {
                return this.ghsPriceField;
            }
            set {
                if ((this.ghsPriceField.Equals(value) != true)) {
                    this.ghsPriceField = value;
                    this.RaisePropertyChanged("ghsPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.ArrayOfIndicator indicators {
            get {
                return this.indicatorsField;
            }
            set {
                if ((object.ReferenceEquals(this.indicatorsField, value) != true)) {
                    this.indicatorsField = value;
                    this.RaisePropertyChanged("indicators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceUcd.MarketStatus> marketStatus {
            get {
                return this.marketStatusField;
            }
            set {
                if ((this.marketStatusField.Equals(value) != true)) {
                    this.marketStatusField = value;
                    this.RaisePropertyChanged("marketStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool retrocession {
            get {
                return this.retrocessionField;
            }
            set {
                if ((this.retrocessionField.Equals(value) != true)) {
                    this.retrocessionField = value;
                    this.RaisePropertyChanged("retrocession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> retrocessionPrice {
            get {
                return this.retrocessionPriceField;
            }
            set {
                if ((this.retrocessionPriceField.Equals(value) != true)) {
                    this.retrocessionPriceField = value;
                    this.RaisePropertyChanged("retrocessionPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfIndicator", Namespace="urn:Vidal", ItemName="indicator")]
    [System.SerializableAttribute()]
    public class ArrayOfIndicator : System.Collections.Generic.List<ExemplePoso.ServiceUcd.indicator> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="indicator", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class indicator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string indicatorValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string indicatorValue {
            get {
                return this.indicatorValueField;
            }
            set {
                if ((object.ReferenceEquals(this.indicatorValueField, value) != true)) {
                    this.indicatorValueField = value;
                    this.RaisePropertyChanged("indicatorValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUcdPosologyUnitsAndItemsConcentrations", Namespace="urn:Vidal", ItemName="ucdPosologyUnitsAndItemsConcentrations")]
    [System.SerializableAttribute()]
    public class ArrayOfUcdPosologyUnitsAndItemsConcentrations : System.Collections.Generic.List<ExemplePoso.ServiceUcd.ucdPosologyUnitsAndItemsConcentrations> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ucdPosologyUnitsAndItemsConcentrations", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class ucdPosologyUnitsAndItemsConcentrations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string code13Field;
        
        private bool ghsField;
        
        private System.Nullable<System.DateTime> ghsEffectiveDateField;
        
        private System.Nullable<float> ghsPriceField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<ExemplePoso.ServiceUcd.MarketStatus> marketStatusField;
        
        private string nameField;
        
        private bool retrocessionField;
        
        private System.Nullable<System.DateTime> retrocessionEffectiveDateField;
        
        private System.Nullable<float> retrocessionPriceField;
        
        private ExemplePoso.ServiceUcd.ArrayOfUcdItem ucdItemsField;
        
        private ExemplePoso.ServiceUcd.ArrayOfUcdPosologyUnit ucdPosologyUnitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code13 {
            get {
                return this.code13Field;
            }
            set {
                if ((object.ReferenceEquals(this.code13Field, value) != true)) {
                    this.code13Field = value;
                    this.RaisePropertyChanged("code13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ghs {
            get {
                return this.ghsField;
            }
            set {
                if ((this.ghsField.Equals(value) != true)) {
                    this.ghsField = value;
                    this.RaisePropertyChanged("ghs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> ghsEffectiveDate {
            get {
                return this.ghsEffectiveDateField;
            }
            set {
                if ((this.ghsEffectiveDateField.Equals(value) != true)) {
                    this.ghsEffectiveDateField = value;
                    this.RaisePropertyChanged("ghsEffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> ghsPrice {
            get {
                return this.ghsPriceField;
            }
            set {
                if ((this.ghsPriceField.Equals(value) != true)) {
                    this.ghsPriceField = value;
                    this.RaisePropertyChanged("ghsPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceUcd.MarketStatus> marketStatus {
            get {
                return this.marketStatusField;
            }
            set {
                if ((this.marketStatusField.Equals(value) != true)) {
                    this.marketStatusField = value;
                    this.RaisePropertyChanged("marketStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool retrocession {
            get {
                return this.retrocessionField;
            }
            set {
                if ((this.retrocessionField.Equals(value) != true)) {
                    this.retrocessionField = value;
                    this.RaisePropertyChanged("retrocession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> retrocessionEffectiveDate {
            get {
                return this.retrocessionEffectiveDateField;
            }
            set {
                if ((this.retrocessionEffectiveDateField.Equals(value) != true)) {
                    this.retrocessionEffectiveDateField = value;
                    this.RaisePropertyChanged("retrocessionEffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> retrocessionPrice {
            get {
                return this.retrocessionPriceField;
            }
            set {
                if ((this.retrocessionPriceField.Equals(value) != true)) {
                    this.retrocessionPriceField = value;
                    this.RaisePropertyChanged("retrocessionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.ArrayOfUcdItem ucdItems {
            get {
                return this.ucdItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ucdItemsField, value) != true)) {
                    this.ucdItemsField = value;
                    this.RaisePropertyChanged("ucdItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.ArrayOfUcdPosologyUnit ucdPosologyUnits {
            get {
                return this.ucdPosologyUnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.ucdPosologyUnitsField, value) != true)) {
                    this.ucdPosologyUnitsField = value;
                    this.RaisePropertyChanged("ucdPosologyUnits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUcdItem", Namespace="urn:Vidal", ItemName="ucdItem")]
    [System.SerializableAttribute()]
    public class ArrayOfUcdItem : System.Collections.Generic.List<ExemplePoso.ServiceUcd.ucdItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUcdPosologyUnit", Namespace="urn:Vidal", ItemName="ucdPosologyUnit")]
    [System.SerializableAttribute()]
    public class ArrayOfUcdPosologyUnit : System.Collections.Generic.List<ExemplePoso.ServiceUcd.ucdPosologyUnit> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ucdItem", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class ucdItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceUcd.ArrayOfActiveSubstanceInformation activeSubstanceInformationsField;
        
        private string fullNameField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.ArrayOfActiveSubstanceInformation activeSubstanceInformations {
            get {
                return this.activeSubstanceInformationsField;
            }
            set {
                if ((object.ReferenceEquals(this.activeSubstanceInformationsField, value) != true)) {
                    this.activeSubstanceInformationsField = value;
                    this.RaisePropertyChanged("activeSubstanceInformations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfActiveSubstanceInformation", Namespace="urn:Vidal", ItemName="activeSubstanceInformation")]
    [System.SerializableAttribute()]
    public class ArrayOfActiveSubstanceInformation : System.Collections.Generic.List<ExemplePoso.ServiceUcd.activeSubstanceInformation> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="activeSubstanceInformation", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class activeSubstanceInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceUcd.posologyUnit concentrationUnitField;
        
        private System.Nullable<float> concentrationValueField;
        
        private ExemplePoso.ServiceUcd.molecule moleculeField;
        
        private System.Nullable<float> quantityField;
        
        private ExemplePoso.ServiceUcd.posologyUnit quantityUnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.posologyUnit concentrationUnit {
            get {
                return this.concentrationUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.concentrationUnitField, value) != true)) {
                    this.concentrationUnitField = value;
                    this.RaisePropertyChanged("concentrationUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> concentrationValue {
            get {
                return this.concentrationValueField;
            }
            set {
                if ((this.concentrationValueField.Equals(value) != true)) {
                    this.concentrationValueField = value;
                    this.RaisePropertyChanged("concentrationValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.molecule molecule {
            get {
                return this.moleculeField;
            }
            set {
                if ((object.ReferenceEquals(this.moleculeField, value) != true)) {
                    this.moleculeField = value;
                    this.RaisePropertyChanged("molecule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.posologyUnit quantityUnit {
            get {
                return this.quantityUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.quantityUnitField, value) != true)) {
                    this.quantityUnitField = value;
                    this.RaisePropertyChanged("quantityUnit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="posologyUnit", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class posologyUnit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="molecule", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class molecule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool allergyAlertField;
        
        private bool homeopathyField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        private System.Nullable<ExemplePoso.ServiceUcd.SubstanceRole> roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool allergyAlert {
            get {
                return this.allergyAlertField;
            }
            set {
                if ((this.allergyAlertField.Equals(value) != true)) {
                    this.allergyAlertField = value;
                    this.RaisePropertyChanged("allergyAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool homeopathy {
            get {
                return this.homeopathyField;
            }
            set {
                if ((this.homeopathyField.Equals(value) != true)) {
                    this.homeopathyField = value;
                    this.RaisePropertyChanged("homeopathy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceUcd.SubstanceRole> role {
            get {
                return this.roleField;
            }
            set {
                if ((this.roleField.Equals(value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubstanceRole", Namespace="urn:Vidal")]
    public enum SubstanceRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_PRINCIPLE_OR_EXCIPIENT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXCIPIENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_PRINCIPLE = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ucdPosologyUnit", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class ucdPosologyUnit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceUcd.posologyUnit dispensingUnitField;
        
        private ExemplePoso.ServiceUcd.posologyUnit posologyUnitField;
        
        private System.Nullable<float> ratioOfPosologyUnitOverDispensingUnitField;
        
        private System.Nullable<float> ucdItemQuantityField;
        
        private ExemplePoso.ServiceUcd.posologyUnit ucdItemQuantityUnitField;
        
        private System.Nullable<float> ucdItemVolumeField;
        
        private ExemplePoso.ServiceUcd.posologyUnit ucdItemVolumeUnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.posologyUnit dispensingUnit {
            get {
                return this.dispensingUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.dispensingUnitField, value) != true)) {
                    this.dispensingUnitField = value;
                    this.RaisePropertyChanged("dispensingUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.posologyUnit posologyUnit {
            get {
                return this.posologyUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.posologyUnitField, value) != true)) {
                    this.posologyUnitField = value;
                    this.RaisePropertyChanged("posologyUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> ratioOfPosologyUnitOverDispensingUnit {
            get {
                return this.ratioOfPosologyUnitOverDispensingUnitField;
            }
            set {
                if ((this.ratioOfPosologyUnitOverDispensingUnitField.Equals(value) != true)) {
                    this.ratioOfPosologyUnitOverDispensingUnitField = value;
                    this.RaisePropertyChanged("ratioOfPosologyUnitOverDispensingUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> ucdItemQuantity {
            get {
                return this.ucdItemQuantityField;
            }
            set {
                if ((this.ucdItemQuantityField.Equals(value) != true)) {
                    this.ucdItemQuantityField = value;
                    this.RaisePropertyChanged("ucdItemQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.posologyUnit ucdItemQuantityUnit {
            get {
                return this.ucdItemQuantityUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ucdItemQuantityUnitField, value) != true)) {
                    this.ucdItemQuantityUnitField = value;
                    this.RaisePropertyChanged("ucdItemQuantityUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> ucdItemVolume {
            get {
                return this.ucdItemVolumeField;
            }
            set {
                if ((this.ucdItemVolumeField.Equals(value) != true)) {
                    this.ucdItemVolumeField = value;
                    this.RaisePropertyChanged("ucdItemVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceUcd.posologyUnit ucdItemVolumeUnit {
            get {
                return this.ucdItemVolumeUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ucdItemVolumeUnitField, value) != true)) {
                    this.ucdItemVolumeUnitField = value;
                    this.RaisePropertyChanged("ucdItemVolumeUnit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Vidal", ConfigurationName="ServiceUcd.ucdService")]
    public interface ucdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchByIds(ExemplePoso.ServiceUcd.ArrayOfInt ucdIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pagedResultUcd")]
        ExemplePoso.ServiceUcd.pagedResultUcd getAllUcds(System.Nullable<ExemplePoso.ServiceUcd.UcdApiFilter> ucdApiFilter, ExemplePoso.ServiceUcd.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ProductRangeUcdCoupleList")]
        ExemplePoso.ServiceUcd.ArrayOfProductRangeUcdCouple searchByProductRangeIds(ExemplePoso.ServiceUcd.ArrayOfInt productRangeIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchByProductId(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchByCommonNameGroupId(System.Nullable<int> commonNameGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucd")]
        ExemplePoso.ServiceUcd.ucd searchById(System.Nullable<int> ucdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchByCodes(ExemplePoso.ServiceUcd.ArrayOfString codes);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchNewlyAvailableUcds();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucd")]
        ExemplePoso.ServiceUcd.ucd searchByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchByCompanyIdAndType(System.Nullable<int> companyId, System.Nullable<ExemplePoso.ServiceUcd.CompanyType> type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdIndicatorsList")]
        ExemplePoso.ServiceUcd.ArrayOfUcdIndicators searchUcdIndicatorsByUcdIds(ExemplePoso.ServiceUcd.ArrayOfInt ucdIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucd")]
        ExemplePoso.ServiceUcd.ucd searchByPackId(System.Nullable<int> packId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdList")]
        ExemplePoso.ServiceUcd.ArrayOfUcd searchByCompanyId(System.Nullable<int> companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ucdPosologyUnitsAndItemsConcentrationsList")]
        ExemplePoso.ServiceUcd.ArrayOfUcdPosologyUnitsAndItemsConcentrations getUcdsPosologyUnitsAndItemsConcentrationsByUcdIds(ExemplePoso.ServiceUcd.ArrayOfInt ucdIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pagedResultUcd")]
        ExemplePoso.ServiceUcd.pagedResultUcd searchByNameWithPagedResult(string name, ExemplePoso.ServiceUcd.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ucdServiceChannel : ExemplePoso.ServiceUcd.ucdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ucdServiceClient : System.ServiceModel.ClientBase<ExemplePoso.ServiceUcd.ucdService>, ExemplePoso.ServiceUcd.ucdService {
        
        public ucdServiceClient() {
        }
        
        public ucdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ucdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ucdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ucdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchByIds(ExemplePoso.ServiceUcd.ArrayOfInt ucdIds) {
            return base.Channel.searchByIds(ucdIds);
        }
        
        public ExemplePoso.ServiceUcd.pagedResultUcd getAllUcds(System.Nullable<ExemplePoso.ServiceUcd.UcdApiFilter> ucdApiFilter, ExemplePoso.ServiceUcd.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize) {
            return base.Channel.getAllUcds(ucdApiFilter, marketStatuses, pageNumber, pageSize);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfProductRangeUcdCouple searchByProductRangeIds(ExemplePoso.ServiceUcd.ArrayOfInt productRangeIds) {
            return base.Channel.searchByProductRangeIds(productRangeIds);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchByProductId(System.Nullable<int> productId) {
            return base.Channel.searchByProductId(productId);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchByCommonNameGroupId(System.Nullable<int> commonNameGroupId) {
            return base.Channel.searchByCommonNameGroupId(commonNameGroupId);
        }
        
        public ExemplePoso.ServiceUcd.ucd searchById(System.Nullable<int> ucdId) {
            return base.Channel.searchById(ucdId);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchByCodes(ExemplePoso.ServiceUcd.ArrayOfString codes) {
            return base.Channel.searchByCodes(codes);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchNewlyAvailableUcds() {
            return base.Channel.searchNewlyAvailableUcds();
        }
        
        public ExemplePoso.ServiceUcd.ucd searchByCode(string code) {
            return base.Channel.searchByCode(code);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchByCompanyIdAndType(System.Nullable<int> companyId, System.Nullable<ExemplePoso.ServiceUcd.CompanyType> type) {
            return base.Channel.searchByCompanyIdAndType(companyId, type);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchByName(string name) {
            return base.Channel.searchByName(name);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcdIndicators searchUcdIndicatorsByUcdIds(ExemplePoso.ServiceUcd.ArrayOfInt ucdIds) {
            return base.Channel.searchUcdIndicatorsByUcdIds(ucdIds);
        }
        
        public ExemplePoso.ServiceUcd.ucd searchByPackId(System.Nullable<int> packId) {
            return base.Channel.searchByPackId(packId);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcd searchByCompanyId(System.Nullable<int> companyId) {
            return base.Channel.searchByCompanyId(companyId);
        }
        
        public ExemplePoso.ServiceUcd.ArrayOfUcdPosologyUnitsAndItemsConcentrations getUcdsPosologyUnitsAndItemsConcentrationsByUcdIds(ExemplePoso.ServiceUcd.ArrayOfInt ucdIds) {
            return base.Channel.getUcdsPosologyUnitsAndItemsConcentrationsByUcdIds(ucdIds);
        }
        
        public ExemplePoso.ServiceUcd.pagedResultUcd searchByNameWithPagedResult(string name, ExemplePoso.ServiceUcd.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize) {
            return base.Channel.searchByNameWithPagedResult(name, marketStatuses, pageNumber, pageSize);
        }
    }
}
