//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplePoso.ServiceAllergy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="urn:Vidal", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commonNameGroupMoleculeCouples", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class commonNameGroupMoleculeCouples : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple activeExcipientMoleculeAlertsField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple activePrincipleMoleculeAlertsField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple othersExcipientMoleculeAlertsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple activeExcipientMoleculeAlerts {
            get {
                return this.activeExcipientMoleculeAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.activeExcipientMoleculeAlertsField, value) != true)) {
                    this.activeExcipientMoleculeAlertsField = value;
                    this.RaisePropertyChanged("activeExcipientMoleculeAlerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple activePrincipleMoleculeAlerts {
            get {
                return this.activePrincipleMoleculeAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.activePrincipleMoleculeAlertsField, value) != true)) {
                    this.activePrincipleMoleculeAlertsField = value;
                    this.RaisePropertyChanged("activePrincipleMoleculeAlerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple othersExcipientMoleculeAlerts {
            get {
                return this.othersExcipientMoleculeAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.othersExcipientMoleculeAlertsField, value) != true)) {
                    this.othersExcipientMoleculeAlertsField = value;
                    this.RaisePropertyChanged("othersExcipientMoleculeAlerts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCommonNameGroupMoleculeCouple", Namespace="urn:Vidal", ItemName="commonNameGroupMoleculeCouple")]
    [System.SerializableAttribute()]
    public class ArrayOfCommonNameGroupMoleculeCouple : System.Collections.Generic.List<ExemplePoso.ServiceAllergy.commonNameGroupMoleculeCouple> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commonNameGroupMoleculeCouple", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class commonNameGroupMoleculeCouple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyLinkedField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyPatientField;
        
        private ExemplePoso.ServiceAllergy.commonNameGroup commonNameGroupField;
        
        private ExemplePoso.ServiceAllergy.molecule moleculeField;
        
        private ExemplePoso.ServiceAllergy.molecule moleculePatientField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.SubstanceType> typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergy {
            get {
                return this.allergyField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyField, value) != true)) {
                    this.allergyField = value;
                    this.RaisePropertyChanged("allergy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyLinked {
            get {
                return this.allergyLinkedField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyLinkedField, value) != true)) {
                    this.allergyLinkedField = value;
                    this.RaisePropertyChanged("allergyLinked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyPatient {
            get {
                return this.allergyPatientField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyPatientField, value) != true)) {
                    this.allergyPatientField = value;
                    this.RaisePropertyChanged("allergyPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.commonNameGroup commonNameGroup {
            get {
                return this.commonNameGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.commonNameGroupField, value) != true)) {
                    this.commonNameGroupField = value;
                    this.RaisePropertyChanged("commonNameGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.molecule molecule {
            get {
                return this.moleculeField;
            }
            set {
                if ((object.ReferenceEquals(this.moleculeField, value) != true)) {
                    this.moleculeField = value;
                    this.RaisePropertyChanged("molecule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.molecule moleculePatient {
            get {
                return this.moleculePatientField;
            }
            set {
                if ((object.ReferenceEquals(this.moleculePatientField, value) != true)) {
                    this.moleculePatientField = value;
                    this.RaisePropertyChanged("moleculePatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.SubstanceType> type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="allergy", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class allergy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commonNameGroup", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class commonNameGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<float> maxUcdRangePriceField;
        
        private System.Nullable<float> minUcdRangePriceField;
        
        private string nameField;
        
        private bool notHomogeneousByInteractionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> maxUcdRangePrice {
            get {
                return this.maxUcdRangePriceField;
            }
            set {
                if ((this.maxUcdRangePriceField.Equals(value) != true)) {
                    this.maxUcdRangePriceField = value;
                    this.RaisePropertyChanged("maxUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> minUcdRangePrice {
            get {
                return this.minUcdRangePriceField;
            }
            set {
                if ((this.minUcdRangePriceField.Equals(value) != true)) {
                    this.minUcdRangePriceField = value;
                    this.RaisePropertyChanged("minUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool notHomogeneousByInteractions {
            get {
                return this.notHomogeneousByInteractionsField;
            }
            set {
                if ((this.notHomogeneousByInteractionsField.Equals(value) != true)) {
                    this.notHomogeneousByInteractionsField = value;
                    this.RaisePropertyChanged("notHomogeneousByInteractions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="molecule", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class molecule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool allergyAlertField;
        
        private bool homeopathyField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.SubstanceRole> roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool allergyAlert {
            get {
                return this.allergyAlertField;
            }
            set {
                if ((this.allergyAlertField.Equals(value) != true)) {
                    this.allergyAlertField = value;
                    this.RaisePropertyChanged("allergyAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool homeopathy {
            get {
                return this.homeopathyField;
            }
            set {
                if ((this.homeopathyField.Equals(value) != true)) {
                    this.homeopathyField = value;
                    this.RaisePropertyChanged("homeopathy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.SubstanceRole> role {
            get {
                return this.roleField;
            }
            set {
                if ((this.roleField.Equals(value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubstanceType", Namespace="urn:Vidal")]
    public enum SubstanceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_PRINCIPLE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXCIPIENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_EXCIPIENT = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubstanceRole", Namespace="urn:Vidal")]
    public enum SubstanceRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_PRINCIPLE_OR_EXCIPIENT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXCIPIENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_PRINCIPLE = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductMoleculeCouple", Namespace="urn:Vidal", ItemName="productMoleculeCouple")]
    [System.SerializableAttribute()]
    public class ArrayOfProductMoleculeCouple : System.Collections.Generic.List<ExemplePoso.ServiceAllergy.productMoleculeCouple> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productMoleculeCouple", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productMoleculeCouple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyLinkedField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyPatientField;
        
        private System.Nullable<int> idField;
        
        private ExemplePoso.ServiceAllergy.molecule moleculeField;
        
        private ExemplePoso.ServiceAllergy.molecule moleculePatientField;
        
        private ExemplePoso.ServiceAllergy.product productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergy {
            get {
                return this.allergyField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyField, value) != true)) {
                    this.allergyField = value;
                    this.RaisePropertyChanged("allergy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyLinked {
            get {
                return this.allergyLinkedField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyLinkedField, value) != true)) {
                    this.allergyLinkedField = value;
                    this.RaisePropertyChanged("allergyLinked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyPatient {
            get {
                return this.allergyPatientField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyPatientField, value) != true)) {
                    this.allergyPatientField = value;
                    this.RaisePropertyChanged("allergyPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.molecule molecule {
            get {
                return this.moleculeField;
            }
            set {
                if ((object.ReferenceEquals(this.moleculeField, value) != true)) {
                    this.moleculeField = value;
                    this.RaisePropertyChanged("molecule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.molecule moleculePatient {
            get {
                return this.moleculePatientField;
            }
            set {
                if ((object.ReferenceEquals(this.moleculePatientField, value) != true)) {
                    this.moleculePatientField = value;
                    this.RaisePropertyChanged("moleculePatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.AmmType> ammTypeField;
        
        private string cisField;
        
        private System.Nullable<int> commonNameGroupIdField;
        
        private bool drugInSportField;
        
        private bool exceptionalField;
        
        private string flavorField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.GenericType> genericTypeField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.ListType> listField;
        
        private string listValueField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.MarketStatus> marketStatusField;
        
        private System.Nullable<float> maxUcdRangePriceField;
        
        private bool midwifeField;
        
        private System.Nullable<float> minUcdRangePriceField;
        
        private string nameField;
        
        private string perVolumeField;
        
        private string perVolumeUnitField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.RefundRate> refundingRateField;
        
        private string refundingRateValueField;
        
        private bool safetyAlertField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.ProductType> typeField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.Vigilance> vigilanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.AmmType> ammType {
            get {
                return this.ammTypeField;
            }
            set {
                if ((this.ammTypeField.Equals(value) != true)) {
                    this.ammTypeField = value;
                    this.RaisePropertyChanged("ammType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cis {
            get {
                return this.cisField;
            }
            set {
                if ((object.ReferenceEquals(this.cisField, value) != true)) {
                    this.cisField = value;
                    this.RaisePropertyChanged("cis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> commonNameGroupId {
            get {
                return this.commonNameGroupIdField;
            }
            set {
                if ((this.commonNameGroupIdField.Equals(value) != true)) {
                    this.commonNameGroupIdField = value;
                    this.RaisePropertyChanged("commonNameGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool drugInSport {
            get {
                return this.drugInSportField;
            }
            set {
                if ((this.drugInSportField.Equals(value) != true)) {
                    this.drugInSportField = value;
                    this.RaisePropertyChanged("drugInSport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool exceptional {
            get {
                return this.exceptionalField;
            }
            set {
                if ((this.exceptionalField.Equals(value) != true)) {
                    this.exceptionalField = value;
                    this.RaisePropertyChanged("exceptional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string flavor {
            get {
                return this.flavorField;
            }
            set {
                if ((object.ReferenceEquals(this.flavorField, value) != true)) {
                    this.flavorField = value;
                    this.RaisePropertyChanged("flavor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.GenericType> genericType {
            get {
                return this.genericTypeField;
            }
            set {
                if ((this.genericTypeField.Equals(value) != true)) {
                    this.genericTypeField = value;
                    this.RaisePropertyChanged("genericType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.ListType> list {
            get {
                return this.listField;
            }
            set {
                if ((this.listField.Equals(value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string listValue {
            get {
                return this.listValueField;
            }
            set {
                if ((object.ReferenceEquals(this.listValueField, value) != true)) {
                    this.listValueField = value;
                    this.RaisePropertyChanged("listValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.MarketStatus> marketStatus {
            get {
                return this.marketStatusField;
            }
            set {
                if ((this.marketStatusField.Equals(value) != true)) {
                    this.marketStatusField = value;
                    this.RaisePropertyChanged("marketStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> maxUcdRangePrice {
            get {
                return this.maxUcdRangePriceField;
            }
            set {
                if ((this.maxUcdRangePriceField.Equals(value) != true)) {
                    this.maxUcdRangePriceField = value;
                    this.RaisePropertyChanged("maxUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool midwife {
            get {
                return this.midwifeField;
            }
            set {
                if ((this.midwifeField.Equals(value) != true)) {
                    this.midwifeField = value;
                    this.RaisePropertyChanged("midwife");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> minUcdRangePrice {
            get {
                return this.minUcdRangePriceField;
            }
            set {
                if ((this.minUcdRangePriceField.Equals(value) != true)) {
                    this.minUcdRangePriceField = value;
                    this.RaisePropertyChanged("minUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string perVolume {
            get {
                return this.perVolumeField;
            }
            set {
                if ((object.ReferenceEquals(this.perVolumeField, value) != true)) {
                    this.perVolumeField = value;
                    this.RaisePropertyChanged("perVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string perVolumeUnit {
            get {
                return this.perVolumeUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.perVolumeUnitField, value) != true)) {
                    this.perVolumeUnitField = value;
                    this.RaisePropertyChanged("perVolumeUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.RefundRate> refundingRate {
            get {
                return this.refundingRateField;
            }
            set {
                if ((this.refundingRateField.Equals(value) != true)) {
                    this.refundingRateField = value;
                    this.RaisePropertyChanged("refundingRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string refundingRateValue {
            get {
                return this.refundingRateValueField;
            }
            set {
                if ((object.ReferenceEquals(this.refundingRateValueField, value) != true)) {
                    this.refundingRateValueField = value;
                    this.RaisePropertyChanged("refundingRateValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool safetyAlert {
            get {
                return this.safetyAlertField;
            }
            set {
                if ((this.safetyAlertField.Equals(value) != true)) {
                    this.safetyAlertField = value;
                    this.RaisePropertyChanged("safetyAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.ProductType> type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.Vigilance> vigilance {
            get {
                return this.vigilanceField;
            }
            set {
                if ((this.vigilanceField.Equals(value) != true)) {
                    this.vigilanceField = value;
                    this.RaisePropertyChanged("vigilance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmmType", Namespace="http://constant.merlin.vidal.com")]
    public enum AmmType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMM_EURO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMM_FRA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATU_COHORTE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATU_NOM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPORT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHER = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericType", Namespace="urn:Vidal")]
    public enum GenericType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GENERIC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REFERENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListType", Namespace="urn:Vidal")]
    public enum ListType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        I = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        II = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NARCOTIC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_HOMOGENEOUS = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketStatus", Namespace="urn:Vidal")]
    public enum MarketStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AVAILABLE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEW = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED_ONEYEAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO_ONEYEAR = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundRate", Namespace="urn:Vidal")]
    public enum RefundRate : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LPPR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _15 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _35 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _65 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _100 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSPECIFIED = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_HOMOGENEOUS = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="urn:Vidal")]
    public enum ProductType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIDAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIETETIC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VETERINARY = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NON_PHARMACEUTICAL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCESSORY = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MISCELLANEOUS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HOMEOPATHIC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BALNEOLOGY = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vigilance", Namespace="urn:Vidal")]
    public enum Vigilance : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_0 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_5 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSPECIFIED = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAllergy", Namespace="urn:Vidal", ItemName="allergy")]
    [System.SerializableAttribute()]
    public class ArrayOfAllergy : System.Collections.Generic.List<ExemplePoso.ServiceAllergy.allergy> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCommonNameGroupAllergyCouple", Namespace="urn:Vidal", ItemName="commonNameGroupAllergyCouple")]
    [System.SerializableAttribute()]
    public class ArrayOfCommonNameGroupAllergyCouple : System.Collections.Generic.List<ExemplePoso.ServiceAllergy.commonNameGroupAllergyCouple> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commonNameGroupAllergyCouple", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class commonNameGroupAllergyCouple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyLinkedField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyPatientField;
        
        private ExemplePoso.ServiceAllergy.commonNameGroup commonNameGroupField;
        
        private ExemplePoso.ServiceAllergy.molecule moleculeField;
        
        private System.Nullable<ExemplePoso.ServiceAllergy.SubstanceType> typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergy {
            get {
                return this.allergyField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyField, value) != true)) {
                    this.allergyField = value;
                    this.RaisePropertyChanged("allergy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyLinked {
            get {
                return this.allergyLinkedField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyLinkedField, value) != true)) {
                    this.allergyLinkedField = value;
                    this.RaisePropertyChanged("allergyLinked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyPatient {
            get {
                return this.allergyPatientField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyPatientField, value) != true)) {
                    this.allergyPatientField = value;
                    this.RaisePropertyChanged("allergyPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.commonNameGroup commonNameGroup {
            get {
                return this.commonNameGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.commonNameGroupField, value) != true)) {
                    this.commonNameGroupField = value;
                    this.RaisePropertyChanged("commonNameGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.molecule molecule {
            get {
                return this.moleculeField;
            }
            set {
                if ((object.ReferenceEquals(this.moleculeField, value) != true)) {
                    this.moleculeField = value;
                    this.RaisePropertyChanged("molecule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceAllergy.SubstanceType> type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonNameGroupAllergyList", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class CommonNameGroupAllergyList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfAllergy allergiesField;
        
        private bool homogeneousField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfAllergy allergies {
            get {
                return this.allergiesField;
            }
            set {
                if ((object.ReferenceEquals(this.allergiesField, value) != true)) {
                    this.allergiesField = value;
                    this.RaisePropertyChanged("allergies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool homogeneous {
            get {
                return this.homogeneousField;
            }
            set {
                if ((this.homogeneousField.Equals(value) != true)) {
                    this.homogeneousField = value;
                    this.RaisePropertyChanged("homogeneous");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commonNameGroupAllergyCouples", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class commonNameGroupAllergyCouples : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple activeExcipientAllergyAlertsField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple activePrincipleAllergyAlertsField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple othersExcipientAllergyAlertsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple activeExcipientAllergyAlerts {
            get {
                return this.activeExcipientAllergyAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.activeExcipientAllergyAlertsField, value) != true)) {
                    this.activeExcipientAllergyAlertsField = value;
                    this.RaisePropertyChanged("activeExcipientAllergyAlerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple activePrincipleAllergyAlerts {
            get {
                return this.activePrincipleAllergyAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.activePrincipleAllergyAlertsField, value) != true)) {
                    this.activePrincipleAllergyAlertsField = value;
                    this.RaisePropertyChanged("activePrincipleAllergyAlerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple othersExcipientAllergyAlerts {
            get {
                return this.othersExcipientAllergyAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.othersExcipientAllergyAlertsField, value) != true)) {
                    this.othersExcipientAllergyAlertsField = value;
                    this.RaisePropertyChanged("othersExcipientAllergyAlerts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductAllergyCouple", Namespace="urn:Vidal", ItemName="productAllergyCouple")]
    [System.SerializableAttribute()]
    public class ArrayOfProductAllergyCouple : System.Collections.Generic.List<ExemplePoso.ServiceAllergy.productAllergyCouple> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productAllergyCouple", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productAllergyCouple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyLinkedField;
        
        private ExemplePoso.ServiceAllergy.allergy allergyPatientField;
        
        private System.Nullable<int> idField;
        
        private ExemplePoso.ServiceAllergy.molecule moleculeField;
        
        private ExemplePoso.ServiceAllergy.product productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergy {
            get {
                return this.allergyField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyField, value) != true)) {
                    this.allergyField = value;
                    this.RaisePropertyChanged("allergy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyLinked {
            get {
                return this.allergyLinkedField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyLinkedField, value) != true)) {
                    this.allergyLinkedField = value;
                    this.RaisePropertyChanged("allergyLinked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.allergy allergyPatient {
            get {
                return this.allergyPatientField;
            }
            set {
                if ((object.ReferenceEquals(this.allergyPatientField, value) != true)) {
                    this.allergyPatientField = value;
                    this.RaisePropertyChanged("allergyPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.molecule molecule {
            get {
                return this.moleculeField;
            }
            set {
                if ((object.ReferenceEquals(this.moleculeField, value) != true)) {
                    this.moleculeField = value;
                    this.RaisePropertyChanged("molecule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pagedResultAllergy", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class pagedResultAllergy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int pageNumberField;
        
        private int pageSizeField;
        
        private ExemplePoso.ServiceAllergy.ArrayOfAllergy resultField;
        
        private int rowCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceAllergy.ArrayOfAllergy result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int rowCount {
            get {
                return this.rowCountField;
            }
            set {
                if ((this.rowCountField.Equals(value) != true)) {
                    this.rowCountField = value;
                    this.RaisePropertyChanged("rowCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Vidal", ConfigurationName="ServiceAllergy.allergyService")]
    public interface allergyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupMoleculeCouples")]
        ExemplePoso.ServiceAllergy.commonNameGroupMoleculeCouples searchCommonNameGroupAllergyMoleculeAlerts(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt moleculeIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productMoleculeCoupleList")]
        ExemplePoso.ServiceAllergy.ArrayOfProductMoleculeCouple getAlertsOnAllergiesMolecules(ExemplePoso.ServiceAllergy.ArrayOfInt productIds, ExemplePoso.ServiceAllergy.ArrayOfInt moleculeIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="allergyList")]
        ExemplePoso.ServiceAllergy.ArrayOfAllergy searchByMoleculeId(System.Nullable<int> moleculeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="allergyList")]
        ExemplePoso.ServiceAllergy.ArrayOfAllergy searchLinkedAllergyByAllergyId(System.Nullable<int> allergyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupAllergyCoupleList")]
        ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple getAlertsOnCommonNameGroupActivePrincipleAllergiesClass(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt allergyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="allergyList")]
        ExemplePoso.ServiceAllergy.ArrayOfAllergy searchByProductId(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="allergyList")]
        ExemplePoso.ServiceAllergy.CommonNameGroupAllergyList searchByCommonNameGroupId(System.Nullable<int> commonNameGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="allergy")]
        ExemplePoso.ServiceAllergy.allergy searchById(System.Nullable<int> allergyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupAllergyCouples")]
        ExemplePoso.ServiceAllergy.commonNameGroupAllergyCouples searchCommonNameGroupAllergyClassAlerts(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt allergyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productAllergyCoupleList")]
        ExemplePoso.ServiceAllergy.ArrayOfProductAllergyCouple getAlertsOnAllergiesClass(ExemplePoso.ServiceAllergy.ArrayOfInt productIds, ExemplePoso.ServiceAllergy.ArrayOfInt allergyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="allergyList")]
        ExemplePoso.ServiceAllergy.ArrayOfAllergy searchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pagedResultAllergy")]
        ExemplePoso.ServiceAllergy.pagedResultAllergy getAllAllergies(System.Nullable<int> pageNumber, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="commonNameGroupMoleculeCoupleList")]
        ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple getAlertsOnCommonNameGroupActivePrincipleAllergiesMolecules(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt moleculeIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface allergyServiceChannel : ExemplePoso.ServiceAllergy.allergyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class allergyServiceClient : System.ServiceModel.ClientBase<ExemplePoso.ServiceAllergy.allergyService>, ExemplePoso.ServiceAllergy.allergyService {
        
        public allergyServiceClient() {
        }
        
        public allergyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public allergyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public allergyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public allergyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExemplePoso.ServiceAllergy.commonNameGroupMoleculeCouples searchCommonNameGroupAllergyMoleculeAlerts(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt moleculeIds) {
            return base.Channel.searchCommonNameGroupAllergyMoleculeAlerts(commonNameGroupIds, moleculeIds);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfProductMoleculeCouple getAlertsOnAllergiesMolecules(ExemplePoso.ServiceAllergy.ArrayOfInt productIds, ExemplePoso.ServiceAllergy.ArrayOfInt moleculeIds) {
            return base.Channel.getAlertsOnAllergiesMolecules(productIds, moleculeIds);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfAllergy searchByMoleculeId(System.Nullable<int> moleculeId) {
            return base.Channel.searchByMoleculeId(moleculeId);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfAllergy searchLinkedAllergyByAllergyId(System.Nullable<int> allergyId) {
            return base.Channel.searchLinkedAllergyByAllergyId(allergyId);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupAllergyCouple getAlertsOnCommonNameGroupActivePrincipleAllergiesClass(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt allergyIds) {
            return base.Channel.getAlertsOnCommonNameGroupActivePrincipleAllergiesClass(commonNameGroupIds, allergyIds);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfAllergy searchByProductId(System.Nullable<int> productId) {
            return base.Channel.searchByProductId(productId);
        }
        
        public ExemplePoso.ServiceAllergy.CommonNameGroupAllergyList searchByCommonNameGroupId(System.Nullable<int> commonNameGroupId) {
            return base.Channel.searchByCommonNameGroupId(commonNameGroupId);
        }
        
        public ExemplePoso.ServiceAllergy.allergy searchById(System.Nullable<int> allergyId) {
            return base.Channel.searchById(allergyId);
        }
        
        public ExemplePoso.ServiceAllergy.commonNameGroupAllergyCouples searchCommonNameGroupAllergyClassAlerts(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt allergyIds) {
            return base.Channel.searchCommonNameGroupAllergyClassAlerts(commonNameGroupIds, allergyIds);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfProductAllergyCouple getAlertsOnAllergiesClass(ExemplePoso.ServiceAllergy.ArrayOfInt productIds, ExemplePoso.ServiceAllergy.ArrayOfInt allergyIds) {
            return base.Channel.getAlertsOnAllergiesClass(productIds, allergyIds);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfAllergy searchByName(string name) {
            return base.Channel.searchByName(name);
        }
        
        public ExemplePoso.ServiceAllergy.pagedResultAllergy getAllAllergies(System.Nullable<int> pageNumber, System.Nullable<int> pageSize) {
            return base.Channel.getAllAllergies(pageNumber, pageSize);
        }
        
        public ExemplePoso.ServiceAllergy.ArrayOfCommonNameGroupMoleculeCouple getAlertsOnCommonNameGroupActivePrincipleAllergiesMolecules(ExemplePoso.ServiceAllergy.ArrayOfInt commonNameGroupIds, ExemplePoso.ServiceAllergy.ArrayOfInt moleculeIds) {
            return base.Channel.getAlertsOnCommonNameGroupActivePrincipleAllergiesMolecules(commonNameGroupIds, moleculeIds);
        }
    }
}
