//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplePoso.ServiceSmr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSmr", Namespace="urn:Vidal", ItemName="smr")]
    [System.SerializableAttribute()]
    public class ArrayOfSmr : System.Collections.Generic.List<ExemplePoso.ServiceSmr.smr> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="smr", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class smr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string commentField;
        
        private System.DateTime dateField;
        
        private System.Nullable<ExemplePoso.ServiceSmr.SmrDegree> degreeField;
        
        private System.Nullable<int> idField;
        
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceSmr.SmrDegree> degree {
            get {
                return this.degreeField;
            }
            set {
                if ((this.degreeField.Equals(value) != true)) {
                    this.degreeField = value;
                    this.RaisePropertyChanged("degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmrDegree", Namespace="urn:Vidal")]
    public enum SmrDegree : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNDEFINED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INSUFFICIENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOW = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MODERATE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPORTANT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAJOR = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Vidal", ConfigurationName="ServiceSmr.smrService")]
    public interface smrService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="smrList")]
        ExemplePoso.ServiceSmr.ArrayOfSmr searchByProductId(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="smrAsmrAsHTML")]
        string getSmrAsmrAsHTML(System.Nullable<int> productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smrServiceChannel : ExemplePoso.ServiceSmr.smrService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smrServiceClient : System.ServiceModel.ClientBase<ExemplePoso.ServiceSmr.smrService>, ExemplePoso.ServiceSmr.smrService {
        
        public smrServiceClient() {
        }
        
        public smrServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smrServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExemplePoso.ServiceSmr.ArrayOfSmr searchByProductId(System.Nullable<int> productId) {
            return base.Channel.searchByProductId(productId);
        }
        
        public string getSmrAsmrAsHTML(System.Nullable<int> productId) {
            return base.Channel.getSmrAsmrAsHTML(productId);
        }
    }
}
