//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplePoso.ServiceCim10 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCim10", Namespace="urn:Vidal", ItemName="cim10")]
    [System.SerializableAttribute()]
    public class ArrayOfCim10 : System.Collections.Generic.List<ExemplePoso.ServiceCim10.cim10> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cim10", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class cim10 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfIndicationGroup", Namespace="urn:Vidal", ItemName="indicationGroup")]
    [System.SerializableAttribute()]
    public class ArrayOfIndicationGroup : System.Collections.Generic.List<ExemplePoso.ServiceCim10.indicationGroup> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="indicationGroup", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class indicationGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfContraIndication", Namespace="urn:Vidal", ItemName="contraIndication")]
    [System.SerializableAttribute()]
    public class ArrayOfContraIndication : System.Collections.Generic.List<ExemplePoso.ServiceCim10.contraIndication> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="contraIndication", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class contraIndication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Vidal", ConfigurationName="ServiceCim10.cim10Service")]
    public interface cim10Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10List")]
        ExemplePoso.ServiceCim10.ArrayOfCim10 searchByIndicationGroupId(System.Nullable<int> indicationGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10List")]
        ExemplePoso.ServiceCim10.ArrayOfCim10 searchByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10")]
        ExemplePoso.ServiceCim10.cim10 getRootNode();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10")]
        ExemplePoso.ServiceCim10.cim10 getParent(System.Nullable<int> cim10Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="indicationGroupList")]
        ExemplePoso.ServiceCim10.ArrayOfIndicationGroup getIndicationGroup(System.Nullable<int> cim10Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10List")]
        ExemplePoso.ServiceCim10.ArrayOfCim10 searchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10")]
        ExemplePoso.ServiceCim10.cim10 searchById(System.Nullable<int> cim10Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10List")]
        ExemplePoso.ServiceCim10.ArrayOfCim10 getChildren(System.Nullable<int> cim10Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cim10List")]
        ExemplePoso.ServiceCim10.ArrayOfCim10 searchByContraIndicationId(System.Nullable<int> contraIndicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="contraIndicationList")]
        ExemplePoso.ServiceCim10.ArrayOfContraIndication getContraIndication(System.Nullable<int> cim10Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cim10ServiceChannel : ExemplePoso.ServiceCim10.cim10Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cim10ServiceClient : System.ServiceModel.ClientBase<ExemplePoso.ServiceCim10.cim10Service>, ExemplePoso.ServiceCim10.cim10Service {
        
        public cim10ServiceClient() {
        }
        
        public cim10ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cim10ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cim10ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cim10ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExemplePoso.ServiceCim10.ArrayOfCim10 searchByIndicationGroupId(System.Nullable<int> indicationGroupId) {
            return base.Channel.searchByIndicationGroupId(indicationGroupId);
        }
        
        public ExemplePoso.ServiceCim10.ArrayOfCim10 searchByCode(string code) {
            return base.Channel.searchByCode(code);
        }
        
        public ExemplePoso.ServiceCim10.cim10 getRootNode() {
            return base.Channel.getRootNode();
        }
        
        public ExemplePoso.ServiceCim10.cim10 getParent(System.Nullable<int> cim10Id) {
            return base.Channel.getParent(cim10Id);
        }
        
        public ExemplePoso.ServiceCim10.ArrayOfIndicationGroup getIndicationGroup(System.Nullable<int> cim10Id) {
            return base.Channel.getIndicationGroup(cim10Id);
        }
        
        public ExemplePoso.ServiceCim10.ArrayOfCim10 searchByName(string name) {
            return base.Channel.searchByName(name);
        }
        
        public ExemplePoso.ServiceCim10.cim10 searchById(System.Nullable<int> cim10Id) {
            return base.Channel.searchById(cim10Id);
        }
        
        public ExemplePoso.ServiceCim10.ArrayOfCim10 getChildren(System.Nullable<int> cim10Id) {
            return base.Channel.getChildren(cim10Id);
        }
        
        public ExemplePoso.ServiceCim10.ArrayOfCim10 searchByContraIndicationId(System.Nullable<int> contraIndicationId) {
            return base.Channel.searchByContraIndicationId(contraIndicationId);
        }
        
        public ExemplePoso.ServiceCim10.ArrayOfContraIndication getContraIndication(System.Nullable<int> cim10Id) {
            return base.Channel.getContraIndication(cim10Id);
        }
    }
}
