//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplePoso.ServiceProduct {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="urn:Vidal", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductRangeProductCouple", Namespace="urn:Vidal", ItemName="productRangeProductCouple")]
    [System.SerializableAttribute()]
    public class ArrayOfProductRangeProductCouple : System.Collections.Generic.List<ExemplePoso.ServiceProduct.productRangeProductCouple> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productRangeProductCouple", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productRangeProductCouple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceProduct.product productField;
        
        private ExemplePoso.ServiceProduct.productRange productRangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.productRange productRange {
            get {
                return this.productRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.productRangeField, value) != true)) {
                    this.productRangeField = value;
                    this.RaisePropertyChanged("productRange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.AmmType> ammTypeField;
        
        private string cisField;
        
        private System.Nullable<int> commonNameGroupIdField;
        
        private bool drugInSportField;
        
        private bool exceptionalField;
        
        private string flavorField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.GenericType> genericTypeField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.ListType> listField;
        
        private string listValueField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.MarketStatus> marketStatusField;
        
        private System.Nullable<float> maxUcdRangePriceField;
        
        private bool midwifeField;
        
        private System.Nullable<float> minUcdRangePriceField;
        
        private string nameField;
        
        private string perVolumeField;
        
        private string perVolumeUnitField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.RefundRate> refundingRateField;
        
        private string refundingRateValueField;
        
        private bool safetyAlertField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.ProductType> typeField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.Vigilance> vigilanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.AmmType> ammType {
            get {
                return this.ammTypeField;
            }
            set {
                if ((this.ammTypeField.Equals(value) != true)) {
                    this.ammTypeField = value;
                    this.RaisePropertyChanged("ammType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cis {
            get {
                return this.cisField;
            }
            set {
                if ((object.ReferenceEquals(this.cisField, value) != true)) {
                    this.cisField = value;
                    this.RaisePropertyChanged("cis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> commonNameGroupId {
            get {
                return this.commonNameGroupIdField;
            }
            set {
                if ((this.commonNameGroupIdField.Equals(value) != true)) {
                    this.commonNameGroupIdField = value;
                    this.RaisePropertyChanged("commonNameGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool drugInSport {
            get {
                return this.drugInSportField;
            }
            set {
                if ((this.drugInSportField.Equals(value) != true)) {
                    this.drugInSportField = value;
                    this.RaisePropertyChanged("drugInSport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool exceptional {
            get {
                return this.exceptionalField;
            }
            set {
                if ((this.exceptionalField.Equals(value) != true)) {
                    this.exceptionalField = value;
                    this.RaisePropertyChanged("exceptional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string flavor {
            get {
                return this.flavorField;
            }
            set {
                if ((object.ReferenceEquals(this.flavorField, value) != true)) {
                    this.flavorField = value;
                    this.RaisePropertyChanged("flavor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.GenericType> genericType {
            get {
                return this.genericTypeField;
            }
            set {
                if ((this.genericTypeField.Equals(value) != true)) {
                    this.genericTypeField = value;
                    this.RaisePropertyChanged("genericType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.ListType> list {
            get {
                return this.listField;
            }
            set {
                if ((this.listField.Equals(value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string listValue {
            get {
                return this.listValueField;
            }
            set {
                if ((object.ReferenceEquals(this.listValueField, value) != true)) {
                    this.listValueField = value;
                    this.RaisePropertyChanged("listValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.MarketStatus> marketStatus {
            get {
                return this.marketStatusField;
            }
            set {
                if ((this.marketStatusField.Equals(value) != true)) {
                    this.marketStatusField = value;
                    this.RaisePropertyChanged("marketStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> maxUcdRangePrice {
            get {
                return this.maxUcdRangePriceField;
            }
            set {
                if ((this.maxUcdRangePriceField.Equals(value) != true)) {
                    this.maxUcdRangePriceField = value;
                    this.RaisePropertyChanged("maxUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool midwife {
            get {
                return this.midwifeField;
            }
            set {
                if ((this.midwifeField.Equals(value) != true)) {
                    this.midwifeField = value;
                    this.RaisePropertyChanged("midwife");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> minUcdRangePrice {
            get {
                return this.minUcdRangePriceField;
            }
            set {
                if ((this.minUcdRangePriceField.Equals(value) != true)) {
                    this.minUcdRangePriceField = value;
                    this.RaisePropertyChanged("minUcdRangePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string perVolume {
            get {
                return this.perVolumeField;
            }
            set {
                if ((object.ReferenceEquals(this.perVolumeField, value) != true)) {
                    this.perVolumeField = value;
                    this.RaisePropertyChanged("perVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string perVolumeUnit {
            get {
                return this.perVolumeUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.perVolumeUnitField, value) != true)) {
                    this.perVolumeUnitField = value;
                    this.RaisePropertyChanged("perVolumeUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.RefundRate> refundingRate {
            get {
                return this.refundingRateField;
            }
            set {
                if ((this.refundingRateField.Equals(value) != true)) {
                    this.refundingRateField = value;
                    this.RaisePropertyChanged("refundingRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string refundingRateValue {
            get {
                return this.refundingRateValueField;
            }
            set {
                if ((object.ReferenceEquals(this.refundingRateValueField, value) != true)) {
                    this.refundingRateValueField = value;
                    this.RaisePropertyChanged("refundingRateValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool safetyAlert {
            get {
                return this.safetyAlertField;
            }
            set {
                if ((this.safetyAlertField.Equals(value) != true)) {
                    this.safetyAlertField = value;
                    this.RaisePropertyChanged("safetyAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.ProductType> type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.Vigilance> vigilance {
            get {
                return this.vigilanceField;
            }
            set {
                if ((this.vigilanceField.Equals(value) != true)) {
                    this.vigilanceField = value;
                    this.RaisePropertyChanged("vigilance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productRange", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productRange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmmType", Namespace="http://constant.merlin.vidal.com")]
    public enum AmmType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMM_EURO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMM_FRA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATU_COHORTE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATU_NOM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPORT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHER = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericType", Namespace="urn:Vidal")]
    public enum GenericType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GENERIC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REFERENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListType", Namespace="urn:Vidal")]
    public enum ListType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        I = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        II = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NARCOTIC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_HOMOGENEOUS = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketStatus", Namespace="urn:Vidal")]
    public enum MarketStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AVAILABLE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEW = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED_ONEYEAR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHARMACO_ONEYEAR = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundRate", Namespace="urn:Vidal")]
    public enum RefundRate : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LPPR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _15 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _35 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _65 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _100 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSPECIFIED = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_HOMOGENEOUS = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="urn:Vidal")]
    public enum ProductType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIDAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIETETIC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VETERINARY = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NON_PHARMACEUTICAL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCESSORY = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MISCELLANEOUS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HOMEOPATHIC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BALNEOLOGY = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vigilance", Namespace="urn:Vidal")]
    public enum Vigilance : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_0 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIGILANCE_5 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSPECIFIED = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProduct", Namespace="urn:Vidal", ItemName="product")]
    [System.SerializableAttribute()]
    public class ArrayOfProduct : System.Collections.Generic.List<ExemplePoso.ServiceProduct.product> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSubstanceType", Namespace="urn:Vidal", ItemName="SubstanceType")]
    [System.SerializableAttribute()]
    public class ArrayOfSubstanceType : System.Collections.Generic.List<System.Nullable<ExemplePoso.ServiceProduct.SubstanceType>> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubstanceType", Namespace="urn:Vidal")]
    public enum SubstanceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_PRINCIPLE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXCIPIENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVE_EXCIPIENT = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductApiFilter", Namespace="urn:Vidal")]
    public enum ProductApiFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductType", Namespace="urn:Vidal", ItemName="ProductType")]
    [System.SerializableAttribute()]
    public class ArrayOfProductType : System.Collections.Generic.List<System.Nullable<ExemplePoso.ServiceProduct.ProductType>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMarketStatus", Namespace="urn:Vidal", ItemName="MarketStatus")]
    [System.SerializableAttribute()]
    public class ArrayOfMarketStatus : System.Collections.Generic.List<System.Nullable<ExemplePoso.ServiceProduct.MarketStatus>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pagedResultProduct", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class pagedResultProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int pageNumberField;
        
        private int pageSizeField;
        
        private ExemplePoso.ServiceProduct.ArrayOfProduct resultField;
        
        private int rowCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.ArrayOfProduct result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int rowCount {
            get {
                return this.rowCountField;
            }
            set {
                if ((this.rowCountField.Equals(value) != true)) {
                    this.rowCountField = value;
                    this.RaisePropertyChanged("rowCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfRoute", Namespace="urn:Vidal", ItemName="route")]
    [System.SerializableAttribute()]
    public class ArrayOfRoute : System.Collections.Generic.List<ExemplePoso.ServiceProduct.route> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="route", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class route : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        private System.Nullable<int> parentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GalenicForm", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class GalenicForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        private System.Nullable<int> parentIdField;
        
        private bool searchField;
        
        private string shortNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool search {
            get {
                return this.searchField;
            }
            set {
                if ((this.searchField.Equals(value) != true)) {
                    this.searchField = value;
                    this.RaisePropertyChanged("search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.shortNameField, value) != true)) {
                    this.shortNameField = value;
                    this.RaisePropertyChanged("shortName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="urn:Vidal", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSmr", Namespace="urn:Vidal", ItemName="smr")]
    [System.SerializableAttribute()]
    public class ArrayOfSmr : System.Collections.Generic.List<ExemplePoso.ServiceProduct.smr> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="smr", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class smr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string commentField;
        
        private System.DateTime dateField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.SmrDegree> degreeField;
        
        private System.Nullable<int> idField;
        
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.SmrDegree> degree {
            get {
                return this.degreeField;
            }
            set {
                if ((this.degreeField.Equals(value) != true)) {
                    this.degreeField = value;
                    this.RaisePropertyChanged("degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmrDegree", Namespace="urn:Vidal")]
    public enum SmrDegree : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNDEFINED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INSUFFICIENT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOW = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MODERATE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPORTANT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAJOR = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductRouteListCouple", Namespace="urn:Vidal", ItemName="productRouteListCouple")]
    [System.SerializableAttribute()]
    public class ArrayOfProductRouteListCouple : System.Collections.Generic.List<ExemplePoso.ServiceProduct.productRouteListCouple> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productRouteListCouple", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productRouteListCouple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceProduct.product productField;
        
        private ExemplePoso.ServiceProduct.ArrayOfRoute routeListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.ArrayOfRoute routeList {
            get {
                return this.routeListField;
            }
            set {
                if ((object.ReferenceEquals(this.routeListField, value) != true)) {
                    this.routeListField = value;
                    this.RaisePropertyChanged("routeList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductIndicators", Namespace="urn:Vidal", ItemName="productIndicators")]
    [System.SerializableAttribute()]
    public class ArrayOfProductIndicators : System.Collections.Generic.List<ExemplePoso.ServiceProduct.productIndicators> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productIndicators", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class productIndicators : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExemplePoso.ServiceProduct.ArrayOfIndicator indicatorsField;
        
        private ExemplePoso.ServiceProduct.product productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.ArrayOfIndicator indicators {
            get {
                return this.indicatorsField;
            }
            set {
                if ((object.ReferenceEquals(this.indicatorsField, value) != true)) {
                    this.indicatorsField = value;
                    this.RaisePropertyChanged("indicators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfIndicator", Namespace="urn:Vidal", ItemName="indicator")]
    [System.SerializableAttribute()]
    public class ArrayOfIndicator : System.Collections.Generic.List<ExemplePoso.ServiceProduct.indicator> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="indicator", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class indicator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string indicatorValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string indicatorValue {
            get {
                return this.indicatorValueField;
            }
            set {
                if ((object.ReferenceEquals(this.indicatorValueField, value) != true)) {
                    this.indicatorValueField = value;
                    this.RaisePropertyChanged("indicatorValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SafetyAlertStatus", Namespace="urn:Vidal")]
    public enum SafetyAlertStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YES = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAVAILABLE = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrescriptionMode", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class PrescriptionMode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool deliveryRestrictedToHospitalField;
        
        private System.Nullable<int> durationField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.UnitType> durationUnitField;
        
        private bool initiallyPrescribedByHospitalField;
        
        private bool initiallyPrescribedBySpecialistField;
        
        private bool prescribedByHospitalField;
        
        private bool prescribedBySpecialistField;
        
        private bool renewalBySpecialistField;
        
        private ExemplePoso.ServiceProduct.SpecialistCenter[] specialistCenterListField;
        
        private ExemplePoso.ServiceProduct.Specialist[] specialistListField;
        
        private bool specificMonitoringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool deliveryRestrictedToHospital {
            get {
                return this.deliveryRestrictedToHospitalField;
            }
            set {
                if ((this.deliveryRestrictedToHospitalField.Equals(value) != true)) {
                    this.deliveryRestrictedToHospitalField = value;
                    this.RaisePropertyChanged("deliveryRestrictedToHospital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.UnitType> durationUnit {
            get {
                return this.durationUnitField;
            }
            set {
                if ((this.durationUnitField.Equals(value) != true)) {
                    this.durationUnitField = value;
                    this.RaisePropertyChanged("durationUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool initiallyPrescribedByHospital {
            get {
                return this.initiallyPrescribedByHospitalField;
            }
            set {
                if ((this.initiallyPrescribedByHospitalField.Equals(value) != true)) {
                    this.initiallyPrescribedByHospitalField = value;
                    this.RaisePropertyChanged("initiallyPrescribedByHospital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool initiallyPrescribedBySpecialist {
            get {
                return this.initiallyPrescribedBySpecialistField;
            }
            set {
                if ((this.initiallyPrescribedBySpecialistField.Equals(value) != true)) {
                    this.initiallyPrescribedBySpecialistField = value;
                    this.RaisePropertyChanged("initiallyPrescribedBySpecialist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool prescribedByHospital {
            get {
                return this.prescribedByHospitalField;
            }
            set {
                if ((this.prescribedByHospitalField.Equals(value) != true)) {
                    this.prescribedByHospitalField = value;
                    this.RaisePropertyChanged("prescribedByHospital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool prescribedBySpecialist {
            get {
                return this.prescribedBySpecialistField;
            }
            set {
                if ((this.prescribedBySpecialistField.Equals(value) != true)) {
                    this.prescribedBySpecialistField = value;
                    this.RaisePropertyChanged("prescribedBySpecialist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool renewalBySpecialist {
            get {
                return this.renewalBySpecialistField;
            }
            set {
                if ((this.renewalBySpecialistField.Equals(value) != true)) {
                    this.renewalBySpecialistField = value;
                    this.RaisePropertyChanged("renewalBySpecialist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.SpecialistCenter[] specialistCenterList {
            get {
                return this.specialistCenterListField;
            }
            set {
                if ((object.ReferenceEquals(this.specialistCenterListField, value) != true)) {
                    this.specialistCenterListField = value;
                    this.RaisePropertyChanged("specialistCenterList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ExemplePoso.ServiceProduct.Specialist[] specialistList {
            get {
                return this.specialistListField;
            }
            set {
                if ((object.ReferenceEquals(this.specialistListField, value) != true)) {
                    this.specialistListField = value;
                    this.RaisePropertyChanged("specialistList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool specificMonitoring {
            get {
                return this.specificMonitoringField;
            }
            set {
                if ((this.specificMonitoringField.Equals(value) != true)) {
                    this.specificMonitoringField = value;
                    this.RaisePropertyChanged("specificMonitoring");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitType", Namespace="urn:Vidal")]
    public enum UnitType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNDEFINED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YEARS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MONTHS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEKS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DAYS = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HOURS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MINUTES = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialistCenter", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class SpecialistCenter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Specialist", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class Specialist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAsmr", Namespace="urn:Vidal", ItemName="asmr")]
    [System.SerializableAttribute()]
    public class ArrayOfAsmr : System.Collections.Generic.List<ExemplePoso.ServiceProduct.asmr> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="asmr", Namespace="urn:Vidal")]
    [System.SerializableAttribute()]
    public partial class asmr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string commentField;
        
        private System.DateTime dateField;
        
        private System.Nullable<ExemplePoso.ServiceProduct.AsmrDegree> degreeField;
        
        private System.Nullable<int> idField;
        
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ExemplePoso.ServiceProduct.AsmrDegree> degree {
            get {
                return this.degreeField;
            }
            set {
                if ((this.degreeField.Equals(value) != true)) {
                    this.degreeField = value;
                    this.RaisePropertyChanged("degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsmrDegree", Namespace="urn:Vidal")]
    public enum AsmrDegree : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASMR_I = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASMR_II = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASMR_III = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASMR_IV = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASMR_V = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSPECIFIED = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Vidal", ConfigurationName="ServiceProduct.productService")]
    public interface productService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ProductRangeProductCoupleList")]
        ExemplePoso.ServiceProduct.ArrayOfProductRangeProductCouple searchByProductRangeIds(ExemplePoso.ServiceProduct.ArrayOfInt productRangeIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="product")]
        ExemplePoso.ServiceProduct.product searchById(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByContraIndicationId(System.Nullable<int> contraIndicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByEphmraId(System.Nullable<int> ephmraId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByMoleculeIds(ExemplePoso.ServiceProduct.ArrayOfInt moleculeIds, ExemplePoso.ServiceProduct.ArrayOfSubstanceType substanceTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="product")]
        ExemplePoso.ServiceProduct.product searchByPackId(System.Nullable<int> packId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByDrugInteractionClassId(System.Nullable<int> drugInteractionClassId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchBySaumonId(System.Nullable<int> saumonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByVidalIds(ExemplePoso.ServiceProduct.ArrayOfInt vidalIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchBySideEffectId(System.Nullable<int> sideEffectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchProductsByUcdId(System.Nullable<int> ucdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByCommonNameGroupId(System.Nullable<int> commonNameGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByWarningId(System.Nullable<int> warningId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pagedResultProduct")]
        ExemplePoso.ServiceProduct.pagedResultProduct getAllProducts(System.Nullable<ExemplePoso.ServiceProduct.ProductApiFilter> productApiFilter, ExemplePoso.ServiceProduct.ArrayOfProductType types, ExemplePoso.ServiceProduct.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByNameWithTypes(string name, ExemplePoso.ServiceProduct.ArrayOfProductType types);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByAtcIds(ExemplePoso.ServiceProduct.ArrayOfInt atcIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchBySempId(System.Nullable<int> sempId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByFoodInteractionId(System.Nullable<int> foodInteractionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="routeList")]
        ExemplePoso.ServiceProduct.ArrayOfRoute getRoute(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pagedResultProduct")]
        ExemplePoso.ServiceProduct.pagedResultProduct searchByNameWithPagedResult(string name, ExemplePoso.ServiceProduct.ArrayOfProductType types, ExemplePoso.ServiceProduct.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByIndicationGroupId(System.Nullable<int> indicationGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchBySaumonIds(ExemplePoso.ServiceProduct.ArrayOfInt saumonIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="galenicForm")]
        ExemplePoso.ServiceProduct.GalenicForm getGalenicForm(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByCodes(ExemplePoso.ServiceProduct.ArrayOfString cis);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByIndicationsGroupId(System.Nullable<int> indicationsGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByNameAndType(string name, System.Nullable<ExemplePoso.ServiceProduct.ProductType> type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByVidalId(System.Nullable<int> vidalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchNewlyAvailableProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="smrList")]
        ExemplePoso.ServiceProduct.ArrayOfSmr getSmr(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByCompanyId(System.Nullable<int> companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ProductRouteListCoupleList")]
        ExemplePoso.ServiceProduct.ArrayOfProductRouteListCouple searchProductRoutesCouplesByProductIds(ExemplePoso.ServiceProduct.ArrayOfInt productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByAtcId(System.Nullable<int> atcId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByPrecautionId(System.Nullable<int> precautionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByIds(ExemplePoso.ServiceProduct.ArrayOfInt productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByMoleculeId(System.Nullable<int> moleculeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByIndicationId(System.Nullable<int> indicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productIndicatorsList")]
        ExemplePoso.ServiceProduct.ArrayOfProductIndicators searchProductIndicatorsByProductIds(ExemplePoso.ServiceProduct.ArrayOfInt productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchBySempIds(ExemplePoso.ServiceProduct.ArrayOfInt sempIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByGenericGroupId(System.Nullable<int> genericGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchByMoleculeIdAndType(System.Nullable<int> moleculeId, System.Nullable<ExemplePoso.ServiceProduct.SubstanceType> substanceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="safetyAlertStatus")]
        System.Nullable<ExemplePoso.ServiceProduct.SafetyAlertStatus> hasCommonNameGroupSafetyAlert(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct directSearchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="prescriptionMode")]
        ExemplePoso.ServiceProduct.PrescriptionMode getPrescriptionMode(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchWithoutInteractionsByVidalId(ExemplePoso.ServiceProduct.ArrayOfInt productIds, System.Nullable<int> vidalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="product")]
        ExemplePoso.ServiceProduct.product searchByUcdId(System.Nullable<int> ucdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="product")]
        ExemplePoso.ServiceProduct.product searchByCis(string cis);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="asmrList")]
        ExemplePoso.ServiceProduct.ArrayOfAsmr getAsmr(System.Nullable<int> productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productList")]
        ExemplePoso.ServiceProduct.ArrayOfProduct searchWithoutInteractionsByIndicationId(ExemplePoso.ServiceProduct.ArrayOfInt productIds, System.Nullable<int> indicationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface productServiceChannel : ExemplePoso.ServiceProduct.productService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class productServiceClient : System.ServiceModel.ClientBase<ExemplePoso.ServiceProduct.productService>, ExemplePoso.ServiceProduct.productService {
        
        public productServiceClient() {
        }
        
        public productServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public productServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProductRangeProductCouple searchByProductRangeIds(ExemplePoso.ServiceProduct.ArrayOfInt productRangeIds) {
            return base.Channel.searchByProductRangeIds(productRangeIds);
        }
        
        public ExemplePoso.ServiceProduct.product searchById(System.Nullable<int> productId) {
            return base.Channel.searchById(productId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByContraIndicationId(System.Nullable<int> contraIndicationId) {
            return base.Channel.searchByContraIndicationId(contraIndicationId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByEphmraId(System.Nullable<int> ephmraId) {
            return base.Channel.searchByEphmraId(ephmraId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByMoleculeIds(ExemplePoso.ServiceProduct.ArrayOfInt moleculeIds, ExemplePoso.ServiceProduct.ArrayOfSubstanceType substanceTypes) {
            return base.Channel.searchByMoleculeIds(moleculeIds, substanceTypes);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByName(string name) {
            return base.Channel.searchByName(name);
        }
        
        public ExemplePoso.ServiceProduct.product searchByPackId(System.Nullable<int> packId) {
            return base.Channel.searchByPackId(packId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByDrugInteractionClassId(System.Nullable<int> drugInteractionClassId) {
            return base.Channel.searchByDrugInteractionClassId(drugInteractionClassId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchBySaumonId(System.Nullable<int> saumonId) {
            return base.Channel.searchBySaumonId(saumonId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByVidalIds(ExemplePoso.ServiceProduct.ArrayOfInt vidalIds) {
            return base.Channel.searchByVidalIds(vidalIds);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchBySideEffectId(System.Nullable<int> sideEffectId) {
            return base.Channel.searchBySideEffectId(sideEffectId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchProductsByUcdId(System.Nullable<int> ucdId) {
            return base.Channel.searchProductsByUcdId(ucdId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByCommonNameGroupId(System.Nullable<int> commonNameGroupId) {
            return base.Channel.searchByCommonNameGroupId(commonNameGroupId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByWarningId(System.Nullable<int> warningId) {
            return base.Channel.searchByWarningId(warningId);
        }
        
        public ExemplePoso.ServiceProduct.pagedResultProduct getAllProducts(System.Nullable<ExemplePoso.ServiceProduct.ProductApiFilter> productApiFilter, ExemplePoso.ServiceProduct.ArrayOfProductType types, ExemplePoso.ServiceProduct.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize) {
            return base.Channel.getAllProducts(productApiFilter, types, marketStatuses, pageNumber, pageSize);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByNameWithTypes(string name, ExemplePoso.ServiceProduct.ArrayOfProductType types) {
            return base.Channel.searchByNameWithTypes(name, types);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByAtcIds(ExemplePoso.ServiceProduct.ArrayOfInt atcIds) {
            return base.Channel.searchByAtcIds(atcIds);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchBySempId(System.Nullable<int> sempId) {
            return base.Channel.searchBySempId(sempId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByFoodInteractionId(System.Nullable<int> foodInteractionId) {
            return base.Channel.searchByFoodInteractionId(foodInteractionId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfRoute getRoute(System.Nullable<int> productId) {
            return base.Channel.getRoute(productId);
        }
        
        public ExemplePoso.ServiceProduct.pagedResultProduct searchByNameWithPagedResult(string name, ExemplePoso.ServiceProduct.ArrayOfProductType types, ExemplePoso.ServiceProduct.ArrayOfMarketStatus marketStatuses, System.Nullable<int> pageNumber, System.Nullable<int> pageSize) {
            return base.Channel.searchByNameWithPagedResult(name, types, marketStatuses, pageNumber, pageSize);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByIndicationGroupId(System.Nullable<int> indicationGroupId) {
            return base.Channel.searchByIndicationGroupId(indicationGroupId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchBySaumonIds(ExemplePoso.ServiceProduct.ArrayOfInt saumonIds) {
            return base.Channel.searchBySaumonIds(saumonIds);
        }
        
        public ExemplePoso.ServiceProduct.GalenicForm getGalenicForm(System.Nullable<int> productId) {
            return base.Channel.getGalenicForm(productId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByCodes(ExemplePoso.ServiceProduct.ArrayOfString cis) {
            return base.Channel.searchByCodes(cis);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByIndicationsGroupId(System.Nullable<int> indicationsGroupId) {
            return base.Channel.searchByIndicationsGroupId(indicationsGroupId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByNameAndType(string name, System.Nullable<ExemplePoso.ServiceProduct.ProductType> type) {
            return base.Channel.searchByNameAndType(name, type);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByVidalId(System.Nullable<int> vidalId) {
            return base.Channel.searchByVidalId(vidalId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchNewlyAvailableProducts() {
            return base.Channel.searchNewlyAvailableProducts();
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfSmr getSmr(System.Nullable<int> productId) {
            return base.Channel.getSmr(productId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByCompanyId(System.Nullable<int> companyId) {
            return base.Channel.searchByCompanyId(companyId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProductRouteListCouple searchProductRoutesCouplesByProductIds(ExemplePoso.ServiceProduct.ArrayOfInt productIds) {
            return base.Channel.searchProductRoutesCouplesByProductIds(productIds);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByAtcId(System.Nullable<int> atcId) {
            return base.Channel.searchByAtcId(atcId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByPrecautionId(System.Nullable<int> precautionId) {
            return base.Channel.searchByPrecautionId(precautionId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByIds(ExemplePoso.ServiceProduct.ArrayOfInt productIds) {
            return base.Channel.searchByIds(productIds);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByMoleculeId(System.Nullable<int> moleculeId) {
            return base.Channel.searchByMoleculeId(moleculeId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByIndicationId(System.Nullable<int> indicationId) {
            return base.Channel.searchByIndicationId(indicationId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProductIndicators searchProductIndicatorsByProductIds(ExemplePoso.ServiceProduct.ArrayOfInt productIds) {
            return base.Channel.searchProductIndicatorsByProductIds(productIds);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchBySempIds(ExemplePoso.ServiceProduct.ArrayOfInt sempIds) {
            return base.Channel.searchBySempIds(sempIds);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByGenericGroupId(System.Nullable<int> genericGroupId) {
            return base.Channel.searchByGenericGroupId(genericGroupId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchByMoleculeIdAndType(System.Nullable<int> moleculeId, System.Nullable<ExemplePoso.ServiceProduct.SubstanceType> substanceType) {
            return base.Channel.searchByMoleculeIdAndType(moleculeId, substanceType);
        }
        
        public System.Nullable<ExemplePoso.ServiceProduct.SafetyAlertStatus> hasCommonNameGroupSafetyAlert(System.Nullable<int> productId) {
            return base.Channel.hasCommonNameGroupSafetyAlert(productId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct directSearchByName(string name) {
            return base.Channel.directSearchByName(name);
        }
        
        public ExemplePoso.ServiceProduct.PrescriptionMode getPrescriptionMode(System.Nullable<int> productId) {
            return base.Channel.getPrescriptionMode(productId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchWithoutInteractionsByVidalId(ExemplePoso.ServiceProduct.ArrayOfInt productIds, System.Nullable<int> vidalId) {
            return base.Channel.searchWithoutInteractionsByVidalId(productIds, vidalId);
        }
        
        public ExemplePoso.ServiceProduct.product searchByUcdId(System.Nullable<int> ucdId) {
            return base.Channel.searchByUcdId(ucdId);
        }
        
        public ExemplePoso.ServiceProduct.product searchByCis(string cis) {
            return base.Channel.searchByCis(cis);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfAsmr getAsmr(System.Nullable<int> productId) {
            return base.Channel.getAsmr(productId);
        }
        
        public ExemplePoso.ServiceProduct.ArrayOfProduct searchWithoutInteractionsByIndicationId(ExemplePoso.ServiceProduct.ArrayOfInt productIds, System.Nullable<int> indicationId) {
            return base.Channel.searchWithoutInteractionsByIndicationId(productIds, indicationId);
        }
    }
}
